### ISSUE TITLE
[FEAT] Expose grafana on grafana.pathoplexus.org

### ISSUE THREAD

**Issue by corneliusroemer** [pathoplexus/pathoplexus#203]
Discussed here with @theosanderson who doesn't object to the idea: https://loculus.slack.com/archives/C05G172HL6L/p1727880365766569

**Comment by corneliusroemer** [comment]
Done:

<img width="682" alt="Brave Browser 2024-10-04 20 55 45" src="https://github.com/user-attachments/assets/24cf981f-60fe-49c0-b079-c89761a62aee">


```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`grafana.pathplexus.org`)
      priority: 10
      services:
        - name: grafana
          port: 80
```

```
kubectl apply -f grafana-ingressroute.yaml -n monitoring
```

FYI @theosanderson
