### ISSUE TITLE
[FEAT] Add lineage definition files to values.yaml

### ISSUE THREAD

**Issue by fhennig** [pathoplexus/pathoplexus#342]
**Is your feature request related to a problem? Please describe.**
I'd like to have better support for lineage search.

**Describe the solution you'd like**
Please add lineage definitions to the organisms where possible.

Configuration example for `values.yaml`:

```yaml
...
// define lineage definitions at top level:
lineageSystemDefinitions:
  pangoLineage:
    1: https://raw.githubusercontent.com/loculus-project/loculus/refs/heads/lineage-validation/preprocessing/dummy/lineage.yaml
defaultOrganismConfig:
  schema:
    ...
```

```yaml
        // For a metadata field, add the lineage definition key:
        - name: pangoLineage
          initiallyVisible: true
          autocomplete: true
          required: true
          type: string
          lineageSystem: pangoLineage
```

**Describe alternatives you've considered**
n/a

**Additional context**
Relevant links:
- https://github.com/loculus-project/loculus/issues/3074#issuecomment-2538826689
- https://github.com/loculus-project/loculus/pull/3434/files#diff-8c45270b76bf36f08f571b509614d6672984b0604844a487a0ad3ba2ad794943
- https://github.com/loculus-project/loculus/pull/3467
