### ISSUE TITLE
Modify template files to make them easier

### ISSUE THREAD

**Issue by emmahodcroft** [pathoplexus/pathoplexus#345]
Currently our template files on the 'Submit' page contain all fields in alphabetical order (mostly), which is probably totally overwhelming to users.

Now that we have this ability (hooray!) we should aim to make our templates more digestible and clear, while still ensuring people can get to lists of all the fields they _could_ use.

Some ideas:
- Remove most of the fields we currently include, keeping all required fields and probably a few 'high likelihood' fields
- Re order fields so that they are more intuitively sensible for users (at least, there's no reason for them to be alphabetic)
- Ensure there's a clear link that indicates where users can find a list of all fields they could possibly use, on the submission page, since they won't see them in the template anymore

I can add a comment (or anyone can!) about possible lists of fields (and order) to include

**Comment by emmahodcroft** [comment]
Make a template with required and desire fields

**Comment by emmahodcroft** [comment]
Need a little more specifying on the order - suggested 'required' then 'desired'

And maybe some clarification on implementation?

**Comment by fhennig** [comment]
I refreshed my memory! Setting the fields in the template is supported in the values.yaml (https://github.com/loculus-project/loculus/issues/3331) - so to implement this, only changes to the values.yaml are required (i.e. no loculus code changes). 

Example from default organism:

```yaml
...
    schema:
      image: "https://www.un.org/sites/un2.un.org/files/field/image/1583952355.1997.jpg"
      organismName: "Test Dummy Organism"
      metadataTemplate:
        - country
        - date
...
```

If we really just want required+desired, then I guess this should be straightforward to configure!
