### ISSUE TITLE
Ask search engines to not index demo instance?

### ISSUE THREAD

**Issue by chaoran-chen** [pathoplexus/pathoplexus#48]
Do we want search engines to show the demo instance? I feel it's probably better if they don't. If people search for Pathoplexus demo, they should rather find a page (e.g., FAQ?) on pathoplexus.org that tells them where to find the demo instance.

If you agree, we should add a robots.txt for the demo to ask search engines to not index it.

**Comment by theosanderson** [comment]
This sounds good but the robots.txt implementation doesn't sound trivial to me - our website images are not built for a particular branch (and that's a good thing). I guess it would be something with a new thing in the Docker entry point or something. Or getting Astro to dynamically render robots.txt if that's possible.

As an easier alternative we could potnetially use `no-index` (and there's another similar one) meta tags

**Comment by corneliusroemer** [comment]
I think the easiest would be to use a traefik middleware to add `X-Robots-Tag` headers (ChatGPT suggested that but it sounds good!): https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag#xrobotstag

Example middleware (ChatGPT):

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: robots-header
  namespace: traefik
spec:
  headers:
    customResponseHeaders:
      X-Robots-Tag: "noindex, nofollow"
```

While writing this comment I directly implemented it in https://github.com/loculus-project/loculus/pull/2657
